services:
  minio:
    container_name: f1_minio
    image: minio/minio:latest
    ports:
      - "9000:9000"  
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
